### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of undefined

### ISSUE THREAD

**Issue by shizuku723** [Toroxx/atom-chinese-converter#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [atom-chinese-converter](https://github.com/toroxx/atom-chinese-converter) package 1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of undefined

```
At C:\Users\Tianmo\.atom\packages\atom-chinese-converter\lib\chinese-converter.js:80

TypeError: Cannot read property 'getSelectedBufferRanges' of undefined
    at Object.sc2tc (/packages/atom-chinese-converter/lib/chinese-converter.js:80:29)
    at HTMLElement.chineseConverterSc2tc (/packages/atom-chinese-converter/lib/chinese-converter.js:50:51)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:349922)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:348397)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:718183)
    at EventEmitter.t (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:726106)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:11.1.0 chinese-converter:sc2tc (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-chinese-converter 1.0.1 
chinese-translator 1.1.2 
```

**Comment by toroxx** [comment]
Can you show me the steps, how you produce the error?
